### PR TITLE
Steane-Reed-Muller code

### PR DESCRIPTION
**Pull request by Fe-r-oz**
improved SRM(1,r)

Outputs:

```
julia> parity_checks(SteaneReedMuller(1,3))
+ XXXXXXXX
+ ZZZZZZZZ
+ __ZZXXYY
+ _ZXY_ZXY
+ _XZYZY_X

julia> parity_checks(SteaneReedMuller(1,4))
+ XXXXXXXXXXXXXXXX
+ ZZZZZZZZZZZZZZZZ
+ ____ZZZZXXXXYYYY
+ __ZZXXYY__ZZXXYY
+ _ZXY_ZXY_ZXY_ZXY
+ _X_XZYZYZYZY_X_X

julia> parity_checks(SteaneReedMuller(1,5))
+ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
+ ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
+ ________ZZZZZZZZXXXXXXXXYYYYYYYY
+ ____ZZZZXXXXYYYY____ZZZZXXXXYYYY
+ __ZZXXYY__ZZXXYY__ZZXXYY__ZZXXYY
+ _ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY
+ _X_X_X_XZYZYZYZYZYZYZYZY_X_X_X_X
```
canonicalize:
```
julia> canonicalize!(parity_checks(SteaneReedMuller(1,3)))
+ XZ_YZXY_
+ _XZYZY_X
+ _ZXY_ZXY
+ __ZZXXYY
+ ZZZZZZZZ

julia> canonicalize!(parity_checks(Gottesman(3)))
+ XZ_Y_YXZ
+ _XZY_XZY
- _ZXYZ_YX
- __ZZYYXX
+ ZZZZZZZZ
```

### CODE REVIEW

**Comment by Fe-r-oz** [comment]
Added a really strong test for Gottesman Codes in Steane-Reed-Muller, the same test that was used to test the prior Gottesman codes for Steane-Reed-Muller codes at t = 1, t =3, 7

**Comment by Fe-r-oz** [comment]
I was told that the `Stabilizer` can accept two bool arguments, no need to pass ;UINt8 argument, but the following happens when testing for large stabilizer circuits;

`Stabilizer(extended_Hx, extended_Hz)
`

`BoundsError: attempt to access 32-element view(::Vector{UInt8}, 33:64) with eltype UInt8 at index [33]`

**Comment by Fe-r-oz** [comment]
Please note that this: https://github.com/QuantumSavory/QuantumClifford.jl/pull/249#issuecomment-2028227314, is intermittent. It's didn't happened always, but sometimes during checking. 

Even then, I would like to know why it's happening because stabilizer is printed correctly for larger circuits.

**Comment by Fe-r-oz** [comment]
There was merge conflicts so I decided to discard the commits.

**Comment by Krastanov** [comment]
Merge conflicts are normal when something else is being developed in parallel. Restarting with a new PR is not a terrible solution, but frequently a better choice is to rebase the branch or merge into the branch.

In this particular case the merge conflict happened because I added significant new ECC tests to help with a more automated correctness check setup.

In particular, for new codes that have input parameters, they will need to be added to `test_ecc_base.jl`.

**Pull request closed without merging**
