### PR TITLE
Move the test runner to use TestItems.jl

### LINKED ISSUE #328: # Move the test runner to use TestItems.jl [$200]
<details>
<summary><strong>Bug bounty logistic details</strong> (click to expand)</summary>

To claim exclusive time to work on this bounty either post a comment here or message [skrastanov@umass.edu](mailto:skrastanov@umass.edu) with:

- your name
- github username
- **(optional)** a brief list of previous pertinent projects you have engaged in

Currently the project is claimed by `no one` until `...`.

If you want to, you can work on this project without making a claim, however claims are encouraged to give you and other contributors peace of mind. Whoever has made a claim takes precedence when solutions are considered.

You can always propose your own funded project, if you would like to contribute something of value that is not yet covered by an official bounty.
</details>

# Move the test runner to use TestItems.jl [$200]

[TestItems.jl](Move the test runner to use TestItems.jl [$200]) permits more convenient execution of tests from withing an IDE like VSCode. Without significantly rewriting tests and while preserving the use of SafeTestsets, move our test suite to be based around TestItems.jl.

**Required skills**: Understanding of the julia test runner infrastructure.

**Reviewer**: Stefan Krastanov

**Duration**: Expected duration of the project (except potential review overhead)

#### Payout procedure:

The Funding for these bounties comes from the National Science Foundation and from the NSF Center for Quantum Networks. The payouts are managed by the NumFOCUS foundation and processed in bulk once every two months. If you live in a country in which NumFOCUS can make payments, you can participate in this bounty program.

[Click here for more details about the bug bounty program.](https://github.com/QuantumSavory/.github/blob/main/BUG_BOUNTIES.md)

### PR DESCRIPTION
**Pull request by thofma**
Closes #328

Some comments:
- Sometimes I had to encapsulat the whole test file in a `@testitem`. This lead to some indendation changes. Best to look at the PR without whitespace changes: https://github.com/QuantumSavory/QuantumClifford.jl/pull/329/files?diff=unified&w=1.
- TestItems.jl already runs `@testitem` in their own module making the use of SafeTestSet unnecessary (see https://discourse.julialang.org/t/prerelease-of-new-testing-framework-and-test-run-ui-in-vs-code/86355/32).

### CODE REVIEW

**Comment by thofma** [comment]
The error is due to the following:
```
julia> begin
         tgate = pcT
         state = StabMixture(S"X")

         apply!(state, tgate)
         apply!(state, tgate)
         apply!(state, tgate)
         apply!(state, tgate)
         state.destabweights |> values |> collect
       end
1-element Vector{ComplexF64}:
 0.9999999999999998 + 0.0im
```
and the fact that the tests in https://github.com/QuantumSavory/QuantumClifford.jl/blob/master/test/test_nonclifford.jl are *not* run with the current setup on master.

Edit: I change the test to use `isapprox` in https://github.com/QuantumSavory/QuantumClifford.jl/pull/329/commits/f5dfe72ac22d03feb84859a9c0e2ca4b6f0029f5.  Now it passes.

**Comment by Krastanov** [comment]
This is wonderful, thank you! And thanks for noticing the testing bug! I will need a day or so to get back to the office and check how this runs. The reason for the occasional spurious import or `##` is to make these easy to run interactively in VSCode, but I imagine with the VSCode integration for TestItems.jl, this would not be necessary anymore.

**Comment by thofma** [comment]
I just installed vscode and checked that it works. It does! If I were a vscode user, I would change all my packages to use this!

One downside is that the summary is less helpful:
```
Test Summary: |  Pass  Total     Time
Package       | 36020  36020  9m18.9s
     Testing QuantumClifford tests passed 
```
But I think this is something that is worked on upstream, see https://github.com/julia-vscode/TestItemRunner.jl/pull/48. Although this is stalling for over a year now.

**Comment by Krastanov** [comment]
Thanks for taking care of all of this. By any chance, did you have doctest failures inside of the VSCode testrunner (but no doctest failures outside of it)? I seem to be getting such a failure, something to do with how things are sandboxed in VSCode. I left a comment to seemingly related issue https://github.com/julia-vscode/TestItemRunner.jl/issues/49 in the commit I just pushed.

Please message me at skrastanov@umass.edu with your name, email, and link to this PR so I can start processing the bounty (I do them in bulk at the end of each month -- you will get a email by numfocus to fill out a webform with payment details). Thanks for all the help!

**Comment by thofma** [comment]
Yes, I am seeing this too. There are a few instances of `CurrentModule = QuantumClifford.Exper[...]` in the documentation markdown source files. If I remove those, then the tests pass. I could open a PR, but not sure if it breaks the documentation in some other way?

**Comment by Krastanov** [comment]
If you could open that PR, that would be great, thanks! I thought they are necessary for the autodocs, but on actually reading through the corresponding doc files, they seem a bit superfluous... maybe just a remnant of some old documentation.

**Pull request merged**
