### PR TITLE
fix #191: too restrictive typeassert for MixedDestabilizer

### LINKED ISSUE #191: MixedDestabilizer constructor has too restrictive typeassert making it break on subarray input
```
julia> random_destabilizer(5,6) |> stabilizerview |> MixedDestabilizer
ERROR: TypeError: in typeassert, expected QuantumClifford.Tableau{SubArray{UInt8, 1, Vector{UInt8}, Tuple{UnitRange{Int64}}, true}, SubArray{UInt64, 2, Matrix{UInt64}, Tuple{Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}}, got a value of type QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}
Stacktrace:
 [1] MixedDestabilizer(stab::Stabilizer{QuantumClifford.Tableau{SubArray{UInt8, 1, Vector{UInt8}, Tuple{UnitRange{Int64}}, true}, SubArray{UInt64, 2, Matrix{UInt64}, Tuple{Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}}}; undoperm::Bool, reportperm::Bool)
   @ QuantumClifford ~/Documents/ScratchSpace/quantumjulia/QuantumClifford.jl/src/QuantumClifford.jl:558


julia> random_destabilizer(5,6) |> stabilizerview |> copy |> MixedDestabilizer
# works fine
```

This is due to the following line: https://github.com/QuantumSavory/QuantumClifford.jl/blob/55fc8765a0ac0595768bcda47d3621b9edb28e20/src/QuantumClifford.jl#L558

where that `t` is not always of type `T` due to https://github.com/QuantumSavory/QuantumClifford.jl/blob/55fc8765a0ac0595768bcda47d3621b9edb28e20/src/QuantumClifford.jl#L525-L526

If `T` involves subarray views, then `zero` just makes a new tableau directly using arrays, not subarrays (as it should!):

```
julia> typeof(@view rand(5)[1:4])
SubArray{Float64, 1, Vector{Float64}, Tuple{UnitRange{Int64}}, true}

julia> typeof(zero(@view rand(5)[1:4]))
Vector{Float64} (alias for Array{Float64, 1})
```

The type assert is there to help JET, so any fix should be checked for whether it causes inference issues detected by JET (that happens automatically thanks to our CI running `test/test_jet.jl`).

### PR DESCRIPTION
**Pull request by Fe-r-oz**
This now works and all the test passes as well:

```
julia> random_destabilizer(5,6) |> stabilizerview |> MixedDestabilizer
𝒟ℯ𝓈𝓉𝒶𝒷━━
+ Z_____
+ _Z____
+ __Z___
+ ___Z__
+ _____X
𝒳ₗ━━━━━━
+ ZZZZX_
𝒮𝓉𝒶𝒷━━━━
+ XZ_ZZ_
- ZX__Z_
+ __YZZ_
+ Z_ZXZ_
+ _____Z
𝒵ₗ━━━━━━
+ ____Z_
```

The JET errors does not increase as well. Hopefully, this is plausible.

- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.
- [x] All of the automated tests on github pass.

### CODE REVIEW

**Comment by Fe-r-oz** [comment]
The PR is ready for review. Thank you!

P.S. My bad for the rebase.  Initially, I had used `:` after `191` in commit message which didn't pushed the issue to appear in `Development`. However, I noticed simply using `#issue` can make the `issue `appear in `Development.` So, I did the rebase using `reword` to remove `:`  in `hash191:` . But the issue still didn't appear in `Development`...

**Review by Krastanov — CHANGES_REQUESTED** [review]
Could you elaborate why this is necessary? Maybe add tests that would have failed without this change?

**Comment by Krastanov** [comment]
The proper fix for this probably requires better parameterization of the input argument. The issue is that the following `T` is not what is preserved:

```
MixedDestabilizer(::Stabilizer{T}) where {T}
```

Rather what is preserved is the `T` in here:

```
MixedDestabilizer(::Stabilizer{Tableau{P, <:AbstractMatrix{T}}}) where {P, T}
```

Maybe we should define `eltype` for these guys.

```
eltype(::Stabilizer{Tableau{P, <:AbstractMatrix{T}}}) where {P, T} = T
```

**Comment by Fe-r-oz** [comment]
I attempted the suggested approach by defining the following method:

```
Base.eltype(::Stabilizer{Tableau{P, <:AbstractMatrix{T}}}) where {P, T} = T
```
Afterward, I initialized a variable `t` using:
```
t = zeros(eltype(stab), n * 2, n)
```

However, when executing `random_destabilizer(5, 6) |> stabilizerview |> MixedDestabilizer`, I encountered the following warning and error messages:
```
INFO: Given QuantumClifford was explicitly requested, output will be shown live.
WARNING: Method definition eltype(QuantumClifford.Stabilizer{QuantumClifford.Tableau{P, var"#s37"} where var"#s37" <: AbstractArray{T, 2}}) where {P, T} in module QuantumClifford at /home/Desktop/191/QuantumClifford.jl/src/QuantumClifford.jl:408 overwritten at /home/Desktop/191/QuantumClifford.jl/src/QuantumClifford.jl:940.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
```

I have followed your suggestions from https://github.com/QuantumSavory/QuantumClifford.jl/pull/366#pullrequestreview-2332357396 by including a comment to elaborate the changes. 

I hope this is reasonable.

**Comment by Fe-r-oz** [comment]
> Maybe add tests that would have failed without this change?

Thank you! I have added tests that fail on the master branch, which reproduce the error without the need for fancy expressions like `random_destabilizer(5, 6) |> stabilizerview |> MixedDestabilizer`. 

```
ERROR: TypeError: in typeassert, expected QuantumClifford.Tableau{SubArray{UInt8, 1, Vector{UInt8}, Tuple{UnitRange{Int64}}, true}, SubArray{UInt64, 2, Matrix{UInt64}, Tuple{Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}}, got a value of type QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}
Stacktrace:
 [1] MixedDestabilizer(stab::Stabilizer{QuantumClifford.Tableau{SubArray{…}, SubArray{…}}}; undoperm::Bool, reportperm::Bool)
   @ QuantumClifford ~/Desktop/hnEW/QuantumClifford.jl/src/QuantumClifford.jl:574
 [2] top-level scope
```

Consequently, the suggestions from https://github.com/QuantumSavory/QuantumClifford.jl/pull/366#pullrequestreview-2332357396 have been fully incorporated. Thus, this PR resolves #191

- [x] comment elaborating the change
- [x] tests that would have failed (on master branch) without this change

**Comment by Fe-r-oz** [comment]
Yup, the JET and compiler have improved as previously removing `::T `caused some tests to fail. 

Thank you for the simplification.

**Comment by Krastanov** [comment]
Great! Thanks for the fix!

**Pull request merged**
