### PR TITLE
Solve piracies and ambiguities

### PR DESCRIPTION
**Pull request by Tortar**
Part of https://github.com/QuantumSavory/QuantumSavory.jl/pull/143

- [x] The code is properly formatted and commented.

### CODE REVIEW

**Comment by Tortar** [comment]
This should be okay I think

**Comment by Krastanov** [comment]
Do you mind adding a comment to the code explaining why these help or which ambiguity they address? I have to admit, looking at them, I am bewildered, and I will be pretty lost a year from know trying to understand why they were added.

**Comment by Tortar** [comment]
Actually I tested everything again, and that part was unnecessary

**Comment by Tortar** [comment]
I think this can be merged, let me know if it is okay @Krastanov

**Comment by Tortar** [comment]
If you could release a new version of QuantumClifford now that this is merged it will be much appreciated because it will help testing the main pr

**Comment by Krastanov** [comment]
Certainly! I should have done that, my bad!

**Pull request merged**
