### PR TITLE
better bit-wrangling abstraction using less boilerplate

### LINKED ISSUE #113: better bit-wrangling abstraction
In many places in the code you can see

```
    T = eltype(xzs)
    lowbit = T(1)
    ibig = _div(T,i-1)+1
    ismall = _mod(T,i-1)
    ismallm = lowbit<<(ismall)
```

where `ibig` is the index within the array of UIntx and `ismall` is the bit within that UIntx. This is getting too repetitive at this point. Find a better way to write it, abstract it away.

Consult the small symbolic Cliffords (e.g. `sHadamard`) as they have some more abstraction.

### PR DESCRIPTION
**Pull request by Fe-r-oz**
I have also checked that this does not introduce any JET errors. Hopefully, this is closes #113!
 

- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.
- [x] All of the automated tests on github pass.

### CODE REVIEW

**Review by Krastanov — CHANGES_REQUESTED** [review]
This is wonderful!

There are quite a few more places where this is used though:

- apply_noise.jl
- pauli_operator.jl
- project_trace_reset.jl
- QuantumClifford.jl
- symbolic_clifford.jl

Not all of them necessarily need to change, maybe what is done here is appropriate to only some for them.

While this is a big step towards fixing #113, I do not think it is sufficient to call it a fix. It is way less boilerplate, but it still has some amount of boilerplate. But we should merge it before worrying about improving it further -- this will already be pretty useful.

**Comment by Fe-r-oz** [comment]
Thank you for highlighting all the files. I have carefully made the changes at appropriate places. Please do cross check them again as these bit masks are used in the critical places.  Since `.xz` is an unsighed vector for paulis and `.xzs` is unsighed matrix for stabs, using `AbstractArray{<:Unsighed}` helps cover these two cases. Although, `UInt64` is used, but I have kept to `Unsighed` as in some places when `Unsighed `was used for type of `Tₘ`.

I think the PR is ready for review. Thank you.

**Comment by Fe-r-oz** [comment]
P.S. This will be beneficial for #411, as it streamlines several areas by reducing boilerplate code, including in `pauli_frames.jl`.

**Comment by Krastanov** [comment]
Thanks, this is much neater!

**Pull request merged**
