### PR TITLE
Enhancements to GF(2) Linear Algebra: in-place row echelon with pivots, nullspace, and basis for row space

### PR DESCRIPTION
**Pull request by Fe-r-oz**
This PR implements enhancements to the GF(2) Linear Algebra functionality. Inspired by python comprehensive [ldpc.mod2](https://github.com/quantumgizmos/ldpc) functionality. The following functionality are implemented in simple Julia:

1. `gf2_row_echelon_with_pivots!`: return row echelon form, transformation matrix, rank and pivots
2.  `gf2_nullspace`: null space
3. `gf2_rowspace_basis`: basis of the row space

Motivation: Currently, we don't have pure linear algebra implementation of the logical X and logical Z operators for stabilizer CSS code without using `MixedDestabilizer.` Meaning, we can determine the logicals that satisfy the following conditions:  

1. $L_z \in \ker(H_x)$
2. $L_z \notin \text{Im}(H_z^T)$

And

1. $L_x \in \ker(H_z)$
2. $L_x \notin \text{Im}(H_x^T)$

These tools are going to be useful for pure linear algebra implementation of logical operators for CSS stabilizer codes. In general, I think it would nice to have complete set of GF(2) functionality.  I have tested for correctness and also add consistency check with [ldpc](https://github.com/quantumgizmos/ldpc)

Edit:

When the nullity is 0, a [vector is zeros](https://math.stackexchange.com/questions/671722/how-to-find-the-null-space-of-the-matrix-over-finite-field-of-size-2) is convention. In this case, the `ldpc.mod2.nullspace` returns `[]`. I have followed the convention.

- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.
- [x] All of the automated tests on github pass.
- [x] We recently started enforcing formatting checks. If formatting issues are reported in the new code you have written, please correct them.

### CODE REVIEW

**Comment by Fe-r-oz** [comment]
Please help review this PR, thank you!

**Comment by Fe-r-oz** [comment]
Please help review this PR, Thank you!

**Comment by Krastanov** [comment]
These are neat! My main question would be whether these are available already in Nemo and company and if they are faster there. Any insight on that?

**Comment by Fe-r-oz** [comment]
> My main question would be whether these are available already in Nemo and company and if they are faster there.

The row echelon form with pivots is likely not available. They have `echelon_form` for full gaussian elimination.  Nemo methods deal has with `ZZ, QQ, GF` fields, while we only require` GF(2) `mostly as end product.

I think we can add another consistency check: `echelon_form(mat) == matrix(GF(2), gf2_row_echelon_with_pivots!(mat_int, full=true)[1]) ` The echelon form has mat that is GF(2)/FqFieldElemMatrix.

```
julia> using QuantumClifford

julia> using Nemo: echelon_form, matrix, GF

julia> mat = rand(Bool, 100, 100);

julia> mat_int = Matrix{Int}(mat);

julia> nemo_mat = matrix(GF(2), mat);

julia> using BenchmarkTools

julia> @btime echelon_form($nemo_mat)
  249.621 μs (25 allocations: 169.45 KiB)

julia> @btime gf2_row_echelon_with_pivots!($mat_int, full=true)
  22.280 μs (7 allocations: 80.14 KiB)

julia> echelon_form(nemo_mat) == matrix(GF(2), gf2_row_echelon_with_pivots!(mat_int, full=true)[1]) # consistency check, maybe we can add this to the test suite
true 
```

**Comment by Krastanov** [comment]
Yup, this looks great, especially being faster than Nemo (that is surprising). Could you make the following changes:

- [ ] do not export these -- generally I avoid exporting new functionality that is not used anywhere else yet, as it might require changes when we start using it
- [ ] add it to the changelog, but mention it is unexported and experimental
- [ ] put the new tests in a separate file -- I try to have the test files become smaller, so it is easier to interactive work with each one of them

This should be straightforward to merge afterwards. Thanks for the contribution!

**Comment by Krastanov** [comment]
The JET failure is unrelated and fixed on master

**Comment by Fe-r-oz** [comment]
Thank you for you suggestions! I have incorporated all of your suggestions.

**Comment by Krastanov** [comment]
thank you!

**Comment by Fe-r-oz** [comment]
Hi, Stefan!

I’m happy to share that PR #471 utilized the `gf2_row_echelon_with_pivots!` method to calculate the rank of a circulant matrix in-place, which was then used to construct the full rectangular matrix.  Finally, one practical use case of `gf2_row_echelon_with_pivots`! 😅

**Pull request merged**
