### PR TITLE
fix: broken doctests and typos

### PR DESCRIPTION
**Pull request by Fe-r-oz**
This PR implements minor fixes in doctests.

Edit:
- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.
- [x] All of the automated tests on github pass.
- [x] We recently started enforcing formatting checks. If formatting issues are reported in the new code you have written, please correct them.

### CODE REVIEW

**Comment by Krastanov** [comment]
These fixes are much appreciated! But I am also a bit confused: any idea how come these problems were not detected by the test runner?

**Comment by Fe-r-oz** [comment]
The test runner didn't detect these errors because it did not construct the code to check the parameters: the parameters (108,12) were given to it on the platter.

https://github.com/QuantumSavory/QuantumClifford.jl/blob/7b444e90f2474f7e762ff2acdc70142c58bd25ca/ext/QuantumCliffordHeckeExt/lifted_product.jl#L254-L255
To the test runner, this was correct because it was the expected result. It didn't calculate the parameters to verify it, as the calculation step - the code construction => to calculate the parameters was missing. This was a silly error. My bad.

**Comment by Fe-r-oz** [comment]
In the first doctest fix, the group algebra, `GA` and the generators `x` and `y` are not constructed. For multivariate bicycle code, the condition is to have a `z = x*y `as the third generator.  This doctest should have thrown an error because `x` and `y` are not provided to it when constructing the third generator. 

https://github.com/QuantumSavory/QuantumClifford.jl/blob/7b444e90f2474f7e762ff2acdc70142c58bd25ca/ext/QuantumCliffordHeckeExt/lifted_product.jl#L218-L230

**Comment by Krastanov** [comment]
That does not seem to be the correct explanation. It seems these doctests, because they were in an extension, were actually never executed. Hopefully the last commit I pushed fixes that.

Thanks for flagging this issue! That would have been unresolved and untested for a long time otherwise. Good catch!

**Pull request merged**
